version: 2
jobs:
  build:
    working_directory: ~/formatters
    docker:
      - image: circleci/node:7.9
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
      - run: npm run lint
