version: 2.1
jobs:
  build:
    working_directory: ~/formatters
    docker:
      - image: circleci/node:12.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: EsLint
          command: npm run lint
